### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by LulledLion** [TrueCP6/ostw-method-library#1]
IsAI(player): Use is communicate voiceline up instead since its less intrusive than swapping heroes. Voiceline up is preferable since its default binded. Potential issues are if player is spamming voicelines. To fix that, use this method first, and when this fails use the current method as a backup.
Ex.	Communicate(Event Player, Voice Line Up);
	Skip If(Is Communicating(Event Player, Voice Line Up), 1);

PI(): This can be more precise. 314.159/10
Ex.	Set Global Variable(A, Divide(314.159, 10));

**Comment by TrueCP6** [comment]
Added to master.
